export const initialAppContext: AppContextType = {
    allStyles: [],
    setAllStyles: () => {},
    stylesLoading: true,
    setStylesLoading: () => {},
    stylesLoaded: false,
    setStylesLoaded: () => {},
    catersTo: [],
    setCatersTo: () => {},
    catersToLoading: true,
    setCatersToLoading: () => {},
    catersToLoaded: false,
    setCatersToLoaded: () => {},
    placeTypes: [],
    setPlaceTypes: () => {},
    placeTypesLoading: true,
    setPlaceTypesLoading: () => {},
    placeTypesLoaded: false,
    setPlaceTypesLoaded: () => {},
    ageGroups: [],
    setAgeGroups: () => {},
    ageGroupsLoading: true,
    setAgeGroupsLoading: () => {},
    ageGroupsLoaded: false,
    setAgeGroupsLoaded: () => {},
    showPaymentModal: false,
    setShowPaymentModal: () => {},
}