export const availableLocations = [
    'new york, new york',
    'los angeles, california',
    'chicago, illinois',
    'houston, texas',
    'phoenix, arizona',
    'philadelphia, pennsylvania',
    'san Antonio, texas',
    'san Diego, california',
    'dallas, texas',
    'san Jose, california',
    'austin, texas',
    'seattle, washington',
    'portland, oregon',
    'jacksonville, florida',
    'san francisco, california',
]